//! Differential text tests against pi (R18).
//!
//! `tests/golden/pi-widths.json` is generated by `scripts/pi-widths-gen.mjs`
//! from pi's own `visibleWidth`, `truncateToWidth`, and `wrapTextWithAnsi`
//! (`packages/tui/src/utils.ts`). This test feeds the same inputs to
//! `lca_tui::engine::text` and fails on any drift, so the highest-risk
//! copied logic (the width layer) is checked against pi rather than against
//! itself. Escape-sequence placement may differ, so truncation and wrapping
//! compare the stripped text (the visible result).
//!
//! Verifies: R18.

use lca_tui::engine::text::{
    strip_terminal_sequences, truncate_to_width, visible_width, wrap_text_with_ansi,
};

fn strings(value: &serde_json::Value) -> Vec<String> {
    value
        .as_array()
        .map(|items| {
            items
                .iter()
                .map(|item| item.as_str().unwrap_or("").to_string())
                .collect()
        })
        .unwrap_or_default()
}

#[test]
fn lca_text_matches_pi() {
    let raw = include_str!("../../../tests/golden/pi-widths.json");
    let vectors: serde_json::Value = serde_json::from_str(raw).expect("golden vectors parse");
    let mut drift = Vec::new();

    for vector in vectors["widths"].as_array().expect("widths") {
        let text = vector["text"].as_str().expect("text");
        let expected = vector["width"].as_u64().expect("width") as usize;
        let actual = visible_width(text);
        if actual != expected {
            drift.push(format!("width {text:?}: pi {expected}, lca {actual}"));
        }
    }

    for vector in vectors["truncations"].as_array().expect("truncations") {
        let text = vector["text"].as_str().expect("text");
        let max = vector["max"].as_u64().expect("max") as usize;
        let expected = vector["result"].as_str().expect("result");
        let actual = truncate_to_width(text, max, "...", false);
        if strip_terminal_sequences(&actual) != strip_terminal_sequences(expected)
            || visible_width(&actual) != visible_width(expected)
        {
            drift.push(format!(
                "truncate {text:?} @{max}: pi {expected:?}, lca {actual:?}"
            ));
        }
    }

    for vector in vectors["wraps"].as_array().expect("wraps") {
        let text = vector["text"].as_str().expect("text");
        let width = vector["width"].as_u64().expect("width") as usize;
        let expected: Vec<String> = strings(&vector["lines"])
            .iter()
            .map(|line| strip_terminal_sequences(line))
            .collect();
        let actual: Vec<String> = wrap_text_with_ansi(text, width)
            .iter()
            .map(|line| strip_terminal_sequences(line))
            .collect();
        if actual != expected {
            drift.push(format!(
                "wrap {text:?} @{width}: pi {expected:?}, lca {actual:?}"
            ));
        }
    }

    assert!(
        drift.is_empty(),
        "text drift vs pi ({} findings):\n{}",
        drift.len(),
        drift.join("\n")
    );
}
