//! Differential width tests against pi (R18).
//!
//! `tests/golden/pi-widths.json` is generated by `scripts/pi-widths-gen.mjs`
//! from pi's own `visibleWidth` (`packages/tui/src/utils.ts`). This test
//! feeds the same inputs to `lca_tui::engine::text::visible_width` and
//! fails on any drift, so the highest-risk copied logic (the width tables)
//! is checked against pi rather than against itself.
//!
//! Verifies: R18.

use lca_tui::engine::text::visible_width;

#[test]
fn lca_widths_match_pi() {
    let raw = include_str!("../../../tests/golden/pi-widths.json");
    let vectors: Vec<serde_json::Value> = serde_json::from_str(raw).expect("golden vectors parse");
    assert!(!vectors.is_empty(), "the golden file has vectors");

    let mut drift = Vec::new();
    for vector in &vectors {
        let text = vector["text"].as_str().expect("text");
        let expected = vector["width"].as_u64().expect("width") as usize;
        let actual = visible_width(text);
        if actual != expected {
            drift.push(format!("{text:?}: pi {expected}, lca {actual}"));
        }
    }
    assert!(
        drift.is_empty(),
        "width drift vs pi ({} of {}):\n{}",
        drift.len(),
        vectors.len(),
        drift.join("\n")
    );
}
